USE [master]
GO

/****** Object:  Database [PresupuestosDB]    Script Date: 8/6/2022 ******/
CREATE DATABASE [PresupuestosDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'PresupuestosDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\PresupuestosDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'PresupuestosDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\PresupuestosDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [PresupuestosDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [PresupuestosDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [PresupuestosDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [PresupuestosDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [PresupuestosDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [PresupuestosDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [PresupuestosDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [PresupuestosDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [PresupuestosDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [PresupuestosDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [PresupuestosDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [PresupuestosDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [PresupuestosDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [PresupuestosDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [PresupuestosDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [PresupuestosDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [PresupuestosDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [PresupuestosDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [PresupuestosDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [PresupuestosDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [PresupuestosDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [PresupuestosDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [PresupuestosDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [PresupuestosDB] SET RECOVERY FULL 
GO

ALTER DATABASE [PresupuestosDB] SET  MULTI_USER 
GO

ALTER DATABASE [PresupuestosDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [PresupuestosDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [PresupuestosDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [PresupuestosDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [PresupuestosDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [PresupuestosDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [PresupuestosDB] SET QUERY_STORE = OFF
GO

ALTER DATABASE [PresupuestosDB] SET  READ_WRITE 
GO